<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <UserSecretsId>34f912ee-9d2b-4f42-a0ca-dd3f9b3dbe1c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.15" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebhookPayment.Infra\PaymentService.Infra.csproj" />
    <ProjectReference Include="..\WebhookPayments.Application\PaymentService.Application.csproj" />
    <ProjectReference Include="..\WebhookPayments.Domain\PaymentService.Domain.csproj" />
  </ItemGroup>

</Project>
